# Site specific settings
title: "MiloSec"
name: "PercussiveElbow"
keywords: "Key, words, about, this, website"
baseurl: ""
url: "http://percussiveelbow.github.io"
description: "Website description"
cover: "/assets/img/cover.svg"
fanpage_id: ""

# Site general settings
lang: "en"
lang_alternate: "pt_BR"
ssl: false # It will redirect to https

disqus: 
twitter: percussiveelbow
facebook: 
github: percussiveelbow
google:

# Build settings
markdown: kramdown
permalink: /:categories/:title/
